### ISSUE TITLE
Changed code several times in PR, and marked success when shouldn't

### ISSUE THREAD

**Issue by ericwb** [vmware/precaution#142] opened 2019-02-16 09:16 UTC
**Describe the bug**
Something in the precaution scan is messing up when multiple commits are being added to a PR.  On the 3rd or so update of a file, Precaution all the sudden reported Success, when it should still have been fail.  

**To Reproduce**
https://github.com/ericwb/bandit/pull/2/checks

**Expected behavior**
I still expect errors since not all problems were resolved. Namely in this case, it no longer shows the errors on using requests module with verify=False (line 896)

**Screenshots**

**Additional context**

**Comment by ericwb** [comment] 2019-02-16 09:19
I believe the issue is there is a syntax error in the code:

```
browne-a02:travel-preapproval browne$ python test.py 
  File "test.py", line 193
    def Connect(host='localhost', port=443, user='root', pwd,
               ^
SyntaxError: non-default argument follows default argument
```
But Precaution shouldn't report overall status as Success for syntax errors.  So still problem in the reporting here.

**Comment by MVrachev** [comment] 2019-02-18 13:02
Until the third commit in your example you have a lot of issues - 20 to be exact: 
https://github.com/ericwb/bandit/pull/2/commits/f3b41ef88a427a336d561dff3a3fa9ed4b4387c7 the same amount of issues I found running Bandit locally.

Then when you look at the weak_crypto file from the fourth commit you don't get any errors by Precaution and the reason for that is because Bandit has a problem scanning the file "weak_crypto".

![image](https://user-images.githubusercontent.com/16246778/52952726-29225800-338e-11e9-8822-03db7f7295cf.png)

Overall our problem is that we don't get any feedback from Bandit when it has problems with parsing the AST.

**Comment by MVrachev** [comment] 2019-02-18 13:27
It looks like this is not only a problem to code scanned by Bandit but also about code scanned by Gosec.
This is my code: 
![image](https://user-images.githubusercontent.com/16246778/52953959-91266d80-3391-11e9-9399-5e77fb8d8966.png)

when I run go run I get:
![image](https://user-images.githubusercontent.com/16246778/52953973-9daac600-3391-11e9-8a53-90992930b14c.png)

You expect that Precaution will catch this but it did not.

**Comment by MVrachev** [comment] 2019-02-18 15:06
The problem is not that from more than 3 commits Precaution scan screws up but the problem is that Precaution doesn't catch problems from the ASTs used by Bandit and Gosec.

I created a new issue about it https://github.com/vmware/precaution/issues/144
and I think we can close this issue.

**Comment by ericwb** [comment] 2019-02-18 16:34
@MVrachev I don't know why we need another issue for this bug. In my second comment I clearly state root cause related to the syntax error.

**Comment by MVrachev** [comment] 2019-02-19 06:15
I just wanted to clarify the bug in the PR message.

**Comment by MVrachev** [comment] 2019-03-11 08:43
Closed by: 
https://github.com/vmware/precaution/pull/145
and https://github.com/vmware/precaution/pull/154

**Closed** 2019-03-11 08:44 UTC
Labels: bug
